### ISSUE TITLE
Cannot read property 'mq' of undefined

### ISSUE THREAD

**Issue by smeijer** [hydrateio/docz-theme-hydrate#9]
I'm unable to apply this theme because of the error mentioned in the title.

I guess you need to port over this bugfix from the default theme:

https://github.com/pedronauck/docz/commit/5596446 as mentioned at https://github.com/pedronauck/docz/issues/452#issuecomment-439402682

**Comment by jpeters5392** [comment]
@smeijer What version of docz-theme-hydrate did you use and what version of docz are you using?  The changes from the commit that you linked are already in the latest version of this theme so that's likely not the cause if you are running the latest version.

**Comment by smeijer** [comment]
```json
"docz": "^0.13.7",
"docz-theme-hydrate": "^1.5.1",
```

The only thing I change between a working default theme, and enabling this theme, is adding the code below, to `doczrc.js`.

```
  theme: 'docz-theme-hydrate',
```

```
🚨 Whoops, we crashed 🚨
Cannot read property 'mq' of undefined
Stack trace
in Styled(div) (created by Context.Consumer)
in div (created by Styled(div))
in Styled(div) (created by Context.Consumer)
in div (created by Styled(div))
in Styled(div) (created by Context.Consumer)
in Component (created by withSizes(Component))
in withSizes(Component) (created by Context.Consumer)
in div (created by Styled(div))
in Styled(div) (created by Ht)
in je (created by Context.Consumer)
in Docs (created by ze)
in ze (created by Ht)
in Ht (created by Context.Consumer)
in ThemeConfig (created by Vt)
in Vt (created by Route)
in Route (created by Context.Consumer)
in Switch (created by Context.Consumer)
in MDXProvider (created by DocPreview)
in DocPreview (created by Context.Consumer)
in ThemeProvider (created by Context.Consumer)
in ThemeConfig (created by Component)
in Component (created by Theme)
in ScrollToTopBase (created by Route)
in Route (created by withRouter(ScrollToTopBase))
in withRouter(ScrollToTopBase) (created by Theme)
in Router (created by BrowserRouter)
in BrowserRouter (created by Router)
in Router (created by Theme)
in DataServer (created by Theme)
in StateProvider (created by Theme)
in ErrorBoundary (created by Theme)
in Theme (at root.jsx:5)
in Root (created by HotExportedRoot)
in AppContainer (created by HotExportedRoot)
in HotExportedRoot (at app/index.jsx:14)
```

**Comment by smeijer** [comment]
@jpeters5392,

I've added a log statement where the error was comming from, as the debugger doesn't want to break there:


https://github.com/hydrateio/docz-theme-hydrate/blob/4456e8a0872bc594400526cd9d51386656538fba/src/components/shared/Sidebar/Hamburguer.tsx#L83-L86

![image](https://user-images.githubusercontent.com/1196524/54389114-a6946c00-469f-11e9-9e66-0f304a429247.png)

**Comment by jpeters5392** [comment]
@smeijer What happens if you explicitly include docz-theme-default@0.12.16 and then try using the default theme?  Do you get the same error?  It looks like that specific code block was changed between 0.12.16 and 0.12.17, and I'm pretty sure that our theme was forked from around 0.12.12.  I just spun up an example docz site on 0.13.7 though and it worked for me, so it might be related to the content of the MDX files and what they are doing.

**Comment by smeijer** [comment]
Installed `docz-theme-default@0.12.16`, but that just works. Cleared all caches to be sure, but still working.

**Comment by smeijer** [comment]
Removed all my `mdx` files, still `docz-theme-hydrate` is throwing the same error.

Using node `8.11.2` and npm `6.4.1`. Also tried `rm -rf node_modules && yarn && yarn docz:dev`, but same result. (yarn `1.7.0`)

**Comment by smeijer** [comment]
Created a small reproduction case here: https://github.com/smeijer/docz-theme-hydrate-issue-9

That's just the basic example from here: https://github.com/pedronauck/docz/tree/v0.12.4/examples/basic, which worked. After that, I installed this theme, removed `.docz` and `node_modules`, ran `yarn` again, and it stopped working.

**Comment by jpeters5392** [comment]
Awesome, thanks.  I'll pull that down and play around with it

**Comment by jpeters5392** [comment]
It's definitely a versioning issue between our theme and docz.  I backed docz down to 0.12.12 and everything ran fine with our theme.  I'll play around some more and see if I can identify what specific change is causing this.

**Comment by jpeters5392** [comment]
The issue pops up when you go from 0.12.15 to 0.12.16 for docz.  My initial suspicion is that it is related to the upgrade to emotion 10 that was a part of 0.12.16.

**Comment by transitive-bullshit** [comment]
Thanks @smeijer for the concrete repro case!

**Comment by jpeters5392** [comment]
@smeijer I just pushed up 2.0.0-alpha1.  Let me know if that works for you.

**Comment by smeijer** [comment]
As it contains only my changes, I guess it does 👍 	

Thanks for the fast responses.
